# Generated by Django 2.1.1 on 2018-10-11 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170905_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='test',
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
