# Generated by Django 2.1.1 on 2018-10-15 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='upload',
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='data',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
