# Generated by Django 2.1.1 on 2018-10-24 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0009_filemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filemodel',
            name='user',
        ),
    ]
