# Generated by Django 2.1.1 on 2018-10-26 15:26

from django.db import migrations, models
import file_upload.models
import file_upload.upload_validator


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0012_remove_filemodel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='data',
            field=models.FileField(validators=[file_upload.upload_validator.FileValidator(allowed_extensions=('mp3', 'jpg'), max_size=25165824)]),
        ),
    ]
