# Generated by Django 2.1.1 on 2018-10-29 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0014_auto_20181029_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='userProfile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
