# Generated by Django 2.1.1 on 2018-10-29 16:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload', '0016_auto_20181029_1754'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileModel',
            new_name='MusicFileModel',
        ),
    ]
