# Generated by Django 2.1.1 on 2018-10-30 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0004_auto_20181025_1526'),
        ('file_upload', '0022_filemodel_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='project',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='project_manager.Project'),
            preserve_default=False,
        ),
    ]
