# Generated by Django 2.1.1 on 2018-10-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0024_auto_20181030_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='project',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='project_manager.Project'),
            preserve_default=False,
        ),
    ]
