# Generated by Django 2.1.1 on 2018-11-30 16:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('file_upload', '0033_auto_20181129_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='comments',
            field=models.ManyToManyField(related_name='comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='description',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
