# Generated by Django 2.1.1 on 2019-01-10 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0035_remove_filemodel_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='genre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='filemodel',
            name='project_publish_image_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
