# Generated by Django 2.1.1 on 2019-01-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0036_auto_20190110_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='project_publish_image_url',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
