# Generated by Django 2.1.1 on 2019-01-11 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0037_auto_20190110_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filemodel',
            name='project_publish_image_url',
            field=models.CharField(default='https://res.cloudinary.com/easymedicine/image/upload/v1547204544/DefaultSongImage.png', max_length=500, null=True),
        ),
    ]
