# Generated by Django 2.1.1 on 2019-04-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_upload', '0038_auto_20190111_1308'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='isAnEditedSong',
            field=models.BooleanField(null=True),
        ),
    ]
