# Generated by Django 2.1.1 on 2018-11-24 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20181025_0028'),
        ('project_manager', '0006_auto_20181031_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='contributors',
            field=models.ManyToManyField(to='accounts.UserProfile'),
        ),
    ]
