# Generated by Django 2.1.1 on 2018-11-12 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0007_project_contributer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributers', to='accounts.UserProfile'),
        ),
    ]
