# Generated by Django 2.1.1 on 2018-11-13 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181113_0044'),
        ('project_manager', '0008_auto_20181113_0009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributer',
        ),
        migrations.AddField(
            model_name='project',
            name='contributor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contributors', to='accounts.UserProfile'),
        ),
    ]
