# Generated by Django 2.1.1 on 2018-11-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0011_auto_20181113_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='contributor',
            field=models.ManyToManyField(null=True, related_name='contributors', to='accounts.UserProfile'),
        ),
    ]
