# Generated by Django 2.1.1 on 2018-11-13 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20181113_0044'),
        ('project_manager', '0013_auto_20181113_2109'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contributor',
        ),
        migrations.AddField(
            model_name='project',
            name='contributor',
            field=models.ManyToManyField(to='accounts.UserProfile'),
        ),
    ]
