# Generated by Django 2.1.1 on 2018-11-13 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_manager', '0014_auto_20181113_2118'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='contributor',
            new_name='contributors',
        ),
    ]
